Feature/components unit tests
ZupIT/beagle-web-react pull request #138
Opened 2020-09-04 04:10 UTC by hectorcustodiozup

**- What I did**
Added unit testing for some of the default components
**- How I did it**
Created spec files and use cases
**- How to verify it**
Run tests
**- Description for the changelog**

2020-09-04 11:50 UTC, Tiagoperes commented
Hector said he would re-implement this using the new file structure.

2020-09-04 12:25 UTC, hectorcustodiozup commented
This one should already be the one with the new file structure

2020-09-04 14:26 UTC, carolinegoncalveszup commented on packages/beagle-react/src/__tests__/components/__snapshots__/BeagleButton.spec.tsx.snap
> +
Esse arquivo precisa de licença?

2020-09-04 14:34 UTC, hectorcustodiozup commented on packages/beagle-react/src/__tests__/components/__snapshots__/BeagleButton.spec.tsx.snap
> +
Eu coloquei a licença e sempre que rodamos os testes ela é retirada do arquivo, e como não barrou no commit achei que não precisava

2020-09-11 13:38 UTC, pedronaveszup requested changes

2020-09-11 13:38 UTC, pedronaveszup commented on packages/beagle-react/package.json
> +    "styled-components": "^5.1.1"
Estou confuso quanto ao import do styled-components aqui, ele já é importado no package.json da raiz, me parece estranho estar sendo importado nos dois lugares. Se é necessário aqui, não deveríamos tirar o import anterior ?

2020-09-11 13:38 UTC, pedronaveszup commented on packages/beagle-react/src/__tests__/components/BeagleButton.spec.tsx
> +import * as React from 'react'
Temos a real necessidade de importar tudo ? Importar somente o que vai ser usado

2020-09-11 14:07 UTC, hectorcustodiozup commented on packages/beagle-react/package.json
> +    "styled-components": "^5.1.1"
Eu havia percebido isso, mas por algum motivo depois da estrutura nova os testes não rodam sem essa dependência direta no package.json do react assim como a do core que está replicada também. Parece que o jest não 'enxerga' o package.json na raiz dos packages (e eu não consegui achar um jeito ou config de fazer isso). Como o react-native não está usando o styled-componentes talvez remover da raiz não seja problema, só acho que não é específico deste PR.

2020-09-11 14:27 UTC, pedropnaves commented on packages/beagle-react/package.json
> +    "styled-components": "^5.1.1"
Eu não vejo problemas em ajustar neste PR por conta que estamos ajustando as dependências para os testes funcionar, mas tudo bem, podemos fazer em outro PR.

Peço apenas que abra as issues a respeito destes pontos que foram levantados para que sejam ajustados em um PR futuro.

2020-09-14 12:42 UTC, raphaelspimenta approved these changes

2020-09-14 13:56 UTC, pedronaveszup approved these changes

2020-09-14 13:56 UTC, merged