Feature/components rn
ZupIT/beagle-web-react pull request #145
Opened 2020-09-15 14:35 UTC by hectorcustodiozup

**- What I did**
Added default components for React Native library and changed interface imports to common source
**- How I did it**
Besides adding the components now the project structure has a commons/model folder which puts together all the components' interfaces as they are the same for both React and React Native. This PR also updates the imports from local interfaces to this shared source.
**- How to verify it**
Create a project using the new library and its components
**- Description for the changelog**

2020-09-15 17:16 UTC, pedronaveszup requested changes

2020-09-15 17:16 UTC, pedronaveszup commented on packages/beagle-react/src/render/renderer.ts
> +import { map } from 'lodash'
import map from 'lodash/map'

2020-09-15 17:26 UTC, hectorcustodiozup commented on packages/beagle-react-native/src/components/BeagleButton/index.tsx
> +  // To DO: Handle Form Submit Action
Esse TO DO é para aquela issue do form, como o React Native não tem um elemento form o beagle:submitform não funciona e temos que achar um jeito de fazer funcionar, por isso foi aberta uma issue separada. Deixei como comentário apenas para sinalizar

2020-09-15 17:28 UTC, hectorcustodiozup commented on packages/beagle-react-native/src/components/BeagleFutureListView/index.tsx
> +  }, [JSON.stringify(dataSource)])
Essa parte do listview eu usei o mesmo do React pois a maneira de renderizar acabou sendo igual, eu testei e o comportamento foi normal. Tem algum caso específico que acha interessante aplicar para validar?

2020-09-15 17:29 UTC, hectorcustodiozup commented on packages/beagle-react-native/src/components/BeagleModal/index.tsx
> +      elevation: 5,
Não verifiquei os estilos exatamente, só visualmente mesmo. Vou checar outra vez

2020-09-15 17:30 UTC, hectorcustodiozup commented on packages/beagle-react-native/src/components/BeagleSimpleForm/index.tsx
> +  //TO DO: Handle Form Submit Action
O mesmo caso do button, deixei como sinalização. da maneira que está hoje o Simple Form é apenas um wrapper assim como o container. Não quebra mas também ainda não está com a funcionalidade completa.

2020-09-15 17:30 UTC, hectorcustodiozup commented on packages/beagle-react-native/src/components/BeagleTabBar/index.tsx
> +      marginTop: 3,
Não verifiquei os estilos exatamente, só visualmente mesmo. Vou checar outra vez

2020-09-15 17:32 UTC, hectorcustodiozup commented on packages/beagle-react-native/src/components/index.ts
> +}
Eu acabei usando o mesmo nome da const, mas como foi possível desenvolver eles para RN eu acabei fazendo. Não sei se temos eles no mobile.

2020-09-15 17:46 UTC, hectorcustodiozup commented on packages/beagle-react-native/src/components/BeagleContainer/index.tsx
> +        beagleAnalytics.trackEventOnScreenDisappeared(screenAnalyticsEvent)
Eu usei o mesmo evento que está no React Web, pelo que eu entendi ele não faz após o onInit mas sim na função de limpeza do useEffect. O onInit é uma prop que é chamada ou não

2020-09-15 18:27 UTC, raphaelspimenta commented on packages/beagle-react-native/src/components/BeagleContainer/index.tsx
> +        beagleAnalytics.trackEventOnScreenDisappeared(screenAnalyticsEvent)
É isso mesmo, esse evento é executado no unmount do componente.

2020-09-15 18:28 UTC, pedronaveszup commented on packages/beagle-react-native/src/components/BeagleContainer/index.tsx
> +        beagleAnalytics.trackEventOnScreenDisappeared(screenAnalyticsEvent)
Ele já tem um evento sendo disparado no useEffect, que é o trackEventOnScreenAppeared. Não entendi o que é o trackEventOnScreenDisappeared. 
Pelo nome, eu realmente não entendi o que era para ser feito, a screen não sumiu para este evento ser disparado. Ambos os lugares podem estar errado, oq acha ?

2020-09-15 18:31 UTC, raphaelspimenta commented on packages/beagle-react-native/src/components/BeagleSimpleForm/index.tsx
> +  //TO DO: Handle Form Submit Action
Criamos uma issue pra tratar a action de submitForm no React Native (https://github.com/ZupIT/beagle-web-core/issues/230). Nesse PR, acho que pode ir sem a funcionalidade e tratar a issue depois. Até porque acredito que pode mudar algo no core.

2020-09-15 18:34 UTC, hectorcustodiozup commented on packages/beagle-react-native/src/components/BeagleContainer/index.tsx
> +        beagleAnalytics.trackEventOnScreenDisappeared(screenAnalyticsEvent)
Se o track desejado for o que é esperado pela nomenclatura realmente está errado, agora fiquei em dúvida se retiro esses eventos do analytics daqui e o Web o que acham? Essa parte do analytics eu deixei igual mesmo, essa funcionalidade do analytics eu não acompanhei como foi feita.

2020-09-15 18:45 UTC, pedronaveszup commented on packages/beagle-react-native/src/components/BeagleFutureListView/index.tsx
> +  }, [JSON.stringify(dataSource)])
O intuito deste useEffect é executar algo quando o dataSource for alterado, certo ? Meu medo é um dataSource muito grande entrar como parâmetro (string) neste ponto, realmente não sei o que poderia causar de efeito colateral, apenas acho meio estranho. Talvez um teste neste caso seria interessante

2020-09-15 18:47 UTC, pedronaveszup commented on packages/beagle-react-native/src/components/index.ts
> +}
Acho que vale o alinhamento para saber se faz sentido mantê-los no mobile ou não. As plataformas ( Android, iOS e agora RN ) devem estar sincronizadas.

Caso faça sentido manter, minha sugestão é alterar o nome da constante para customComponents ou algo similar.

2020-09-15 18:52 UTC, pedronaveszup commented on packages/beagle-react-native/src/components/BeagleContainer/index.tsx
> +        beagleAnalytics.trackEventOnScreenDisappeared(screenAnalyticsEvent)
Opa, eu olhei novamente o arquivo, e não tinha visto que havia um return antes do código que selecionei ( que ai sim faz sentido, pq executará a função qdo o componente for desmontado ).
```
return () => {
      if (screenAnalyticsEvent && beagleAnalytics)
        beagleAnalytics.trackEventOnScreenDisappeared(screenAnalyticsEvent)
```
Foi erro meu mesmo ao não enxergar o retorno da função 😄

2020-09-15 19:57 UTC, hectorcustodiozup commented on packages/beagle-react-native/src/components/BeagleModal/index.tsx
> +      elevation: 5,
![image](https://user-images.githubusercontent.com/50678762/93258248-628e9580-f774-11ea-9a58-0f770d2aaa0b.png)
Usei o modelo de modal padrão do RN de acordo com a documentação, acredito ser um modal básico de mobile

2020-09-15 20:06 UTC, hectorcustodiozup commented on packages/beagle-react-native/src/components/BeagleTabBar/index.tsx
> +      marginTop: 3,
Ajustado largura dos itens para adequar ao mobile.

2020-09-17 19:22 UTC, Tiagoperes requested changes
Reveja o componente `textInput`. Foi o principal problema neste PR. Você alterou o contrato com o backend, isso não pode acontecer. Seja qual foi o contrato com o backend, vc deve respeitá-lo. Se eles não estão de acordo com seus componentes internos, vc deve adequá-los, mas dentro do código do componente. A interface (contrato) não podem nunca ser mudados.

2020-09-17 19:22 UTC, Tiagoperes commented on packages/common/models/beagle-input.model.ts
> +  isMultiline?: boolean,
Essa propriedade não existe no contrato com o Beagle. Não deveria aparecer na interface de um componente.

2020-09-17 19:22 UTC, Tiagoperes commented on packages/common/models/beagle-webview.model.ts
> +	url: string,
indentação

2020-09-17 19:22 UTC, Tiagoperes commented on packages/beagle-react/src/render/renderer.ts
> +/*
Acredito que vc tenha incluído este arquivo por engano. O arquivo `component.ts` faz referência ao `renderer.ts` do commons e não a esse.

2020-09-17 19:22 UTC, Tiagoperes commented on packages/common/types.ts
> +  localAssetsPath?: Record<string, number>,
Essa propriedade não é válida para o React Web, não deveria estar nesse tipo compartilhado.

2020-09-17 19:22 UTC, Tiagoperes commented on packages/common/utils/commons.styled.ts
> +}
verificar a quantidade de espaços nas linhas acima. Algumas estão com dois espaços consecutivos após o `:`.

2020-09-17 19:22 UTC, Tiagoperes commented on packages/common/utils/primitive.ts
> +/*
Considerando minhas colocações sobre a tipagem errada do textInput, acredito que vc não vai mais precisar deste arquivo.

De qualquer forma, cuidado com os nomes de funções. `evaluateStringBoolean` não indica que vc vai receber uma string e verificar se ela é equivalente ao texto 'true'. Pra saber o que essa função faz, só lendo o código fonte.

Alguns exemplos de nomes que dão uma ideia melhor sobre o que a função faz são: `isTextEquivalentToTrue`, `isSameAsTrue`.

Uma forma de melhorar o entendimento é também adicionando JSDocs à função, dessa forma, a IDE vai exibir um texto explicando a função quando o dev passar o mouse por cima. Exemplo:

```typescript
/**
 * Verifies if the text is equivalent to the string "true", ignoring case.
 * @param text the string to verify
 */
export function isTextEquivalentToTrue(text: string) {
  // ...
}
```

2020-09-17 20:24 UTC, raphaelspimenta commented on packages/beagle-react-native/src/components/BeagleFutureListView/index.tsx
> +  }, [JSON.stringify(dataSource)])
De qualquer forma, se isso for algum problema futuro, teremos que alterar nas implementações do listview no react e rn. Estou resolvendo a conversa mas depois pode-se abrir uma issue pra verificar esse ponto.

2020-09-17 20:25 UTC, raphaelspimenta commented on packages/beagle-react-native/bin/copy-files.js
> +
E ele é! Os outros nos projetos específicos não são utilizados. Excluí ambos.

2020-09-17 20:25 UTC, raphaelspimenta commented on packages/beagle-react-native/src/components/BeagleButton/index.tsx
> +import isArray from 'lodash/isArray'
Done!

2020-09-17 20:27 UTC, raphaelspimenta commented on packages/beagle-react-native/src/components/BeagleButton/index.tsx
> +        style={{ ...styleSheet.fromBffStyles, ...styleSheet.defaultStyles }}>
Fixed!

2020-09-17 20:27 UTC, raphaelspimenta commented on packages/beagle-react-native/src/components/BeagleFutureListView/index.tsx
> +    setShoudlLoadPage(true)
Fixed!

2020-09-17 20:28 UTC, raphaelspimenta commented on packages/beagle-react-native/src/components/BeagleLazy/index.tsx
> +    viewContentManager && viewContentManager.getView().fetch(
Blz! Vamos abrir um PR separado corrigindo React e RN

2020-09-17 20:28 UTC, raphaelspimenta commented on packages/beagle-react-native/src/components/BeagleText/index.tsx
> +        ...styleSheet.defaultStyles,
Fixed!

2020-09-17 20:28 UTC, raphaelspimenta commented on packages/beagle-react-native/src/components/BeagleTouchable/index.tsx
> +      <View style={{ ...styleSheet.fromBffStyles, ...styleSheet.defaultStyles }}>
Fixed!

2020-09-17 20:29 UTC, raphaelspimenta commented on packages/beagle-react-native/src/index.ts
>      // @ts-ignore
Sim! Vamos abrir essa issue no core pra corrigir

2020-09-17 20:29 UTC, raphaelspimenta commented on packages/beagle-react-native/src/index.ts
> +    lifecycles: {
Fixed!

2020-09-17 20:30 UTC, raphaelspimenta commented on packages/beagle-react/src/render/renderer.ts
> +/*
Deleted!

2020-09-17 20:30 UTC, raphaelspimenta commented on packages/common/utils/commons.styled.ts
> +}
Fixed!

2020-09-17 20:30 UTC, raphaelspimenta commented on packages/common/utils/primitive.ts
> +/*
Function deleted!

2020-09-17 20:35 UTC, hectorcustodiozup commented on packages/common/models/beagle-webview.model.ts
> +	url: string,
Aqui está correto, 2 espaços. Pode ser do git?

2020-09-17 21:00 UTC, Tiagoperes requested changes

2020-09-17 21:00 UTC, Tiagoperes commented on packages/common/models/beagle-input.model.ts
> +import { BeagleDefaultComponent } from './types'
Sobre a tipagem aqui:

- `disabled` e `readOnly` devem fazer parte do `BaseTextInputInterface` e não das interfaces `BeagleTextInputInterface` e `BeagleTextAreaInterface `.
- `placeholder` e `type` não podem fazem parte do `BaseTextInputInterface`, pois pertencem apenas ao `BeagleTextInputInterface`.

2020-09-17 21:32 UTC, raphaelspimenta commented on packages/common/models/beagle-input.model.ts
> +import { BeagleDefaultComponent } from './types'
Feito!

2020-09-17 22:06 UTC, hectorcustodiozup commented on packages/common/models/beagle-input.model.ts
> +import { BeagleDefaultComponent } from './types'
Só um ponto aqui, no código do React  o beagle:text-area está como readonly e no input readOnly. Eu alterei tudo para readOnly, acho dificil já ter algo em produção usando especificamente isso mas só pra deixar avisado mesmo.

2020-09-18 13:42 UTC, Tiagoperes approved these changes

2020-09-22 12:57 UTC, Tiagoperes submitted a review, later dismissed

2020-09-28 13:08 UTC, pedronaveszup approved these changes

2020-09-28 13:30 UTC, Tiagoperes approved these changes

2020-09-28 14:19 UTC, merged