Implement more tests to Beagle React
ZupIT/beagle-web-react pull request #157
Opened 2020-10-21 03:05 UTC by osmarpetry

**- What I did**
Implemented new tests for the project. I also made the `disabled` options don't trigger the function anymore when is disabled. 

I tried to test the `onPress` of the button, but it just worked when I change `onPress` prop's name to `onClick`

**- How I did it**
I started to scavenge the issues, then I tried to find something of the code. After a small search, I found tests that just has `snapshot` and `spy` on functions.

**- How to verify it**
You can check the unit tests code

**- Description for the changelog**
Increment new tests to Beagle React Web and when `disabled` is true, it will not trigger the function anymore.

2020-10-21 03:44 UTC, osmarpetry commented
I didn't understand why this PR checks have failed, can someone help me to solve this?

2020-10-21 12:59 UTC, Tiagoperes commented
The checks are broken for anyone outside the team who opens a Pull Request. This is a serious problem and we must fix it asap. It breaks because the external Pull request doesn't have permission to post an automatic commentary with the test results, we should disable this commentary for external Pull Requests.

**About the Pull Request:**
First, thank you for contributing! Most of our tests are in the repository `beagle-web-core`, there we test the core beagle functionalities throughly. Having said that, we are in serious technical debit in regards to tests for the beagle-react and beagle-angular components. Most of the tests we have are only snapshots and are very far from being ideal. We value your attention to this and we'll review your pull request as soon as possible.

2020-10-22 21:05 UTC, Tiagoperes requested changes
There are three problems that came up very often in the code, they are:

- **Overtesting:** testing the dependencies instead of your code itself. Example, test if React passed the property correctly. We know React works, there's no need to test this.
- **Repetition**: testing again features that are already guaranteed to work by a previous test.
- **Too many expectations**: a test should have as few expectations as possible, unit tests should check for one thing and one thing only. Example, you shouldn't test a behavior like "render a modal, click the button to open it, click the button to close it". This type of test is the goal of your e2e tests and not the unit tests. The previous example should actually become 4 different tests:
    - should render modal when isOpen is true
    - should not render modal when isOpen is false
    - close button in modal should call onClose
    - should change modal visibility when isOpen changes

2020-10-23 01:18 UTC, osmarpetry commented on packages/beagle-react/src/__tests__/components/BeagleInput.spec.tsx
> +  var inputStateValue = ''
Sorry, it was accidental

2020-10-23 01:18 UTC, osmarpetry commented on packages/beagle-react/src/__tests__/components/BeagleInput.spec.tsx
> +import React, { useState } from 'react'
Auto import from VSCode, just forgot to remove it

2020-10-23 01:20 UTC, osmarpetry commented on packages/beagle-react/src/__tests__/components/BeagleInput.spec.tsx
> +  var inputStateValue = ''
OMG, what happened to me? Hahaha var are everywhere, i never use it

2020-10-23 01:32 UTC, osmarpetry commented
Thanks you about the comments, I will make those changes during the Friday and weekend.

It's very good to hear from another developer about the bad smells of my unit tests. 

Only one observation from my part, the snapshot tests have two problems (just pointing of view, not a complaint):
- one human should read and understand what is really happening inside the code. With `except` texts you can work around on it, because you are making sure what the users sees. What you're showing or not showing to the user.
- styled-components break the snapshot tests when you make changes on it. After some pull requests are harder to you pay attention if the snapshot changed some place elsewhere.

2020-10-23 12:40 UTC, Tiagoperes commented
> * one human should read and understand what is really happening inside the code. With `except` texts you can work around on it, because you are making sure what the users sees. What you're showing or not showing to the user.

I used to think the exact same thing. I actually came to a point where I wouldn't use snapshots at all. But, in all honesty, as long as the developer really checks the snapshot every time it changes, it's perfectly fine to verify if the rendered content is what we expected. Today I use it only for checking the first rendering. The behavior (things like change something when an element is clicked) should always be tested with query selectors instead of snapshots.

Considering i'm going to use snapshots to check if the first rendering is fine, creating another test that will check the exact same thing, but using query selectors instead is kinda pointless. I do agree, that it's more readable, but having both is redundant and having only the tests based on query selectors will never be as complete as a full snapshot test. Furthermore, snapshot tests are extremely easy to write, when its counterpart is not.

You have a valid point and I'd normally agree that the tests should be more readable than a snapshot. But I think snapshots, when used in the correct places, are a good compromise between readability, completude and easiness of implementation. 

> * styled-components break the snapshot tests when you make changes on it. After some pull requests are harder to you pay attention if the snapshot changed some place elsewhere.

Changes in style should indeed break the snapshot. We want to know, for instance, if a modification produced an undesired behavior like desaligning a text. I see nothing wrong in this, but again, as long as the developer pay attention to the changes reported by the snapshot, and he/she should.

I'm just trying to clarify why we do it like this, the opinions stated here are not just mine, but of the entire team. It can sure be a matter of perspective, but I prefer to explain why instead of just saying "it is because it is".

2020-10-24 02:22 UTC, osmarpetry commented on packages/beagle-react/src/__tests__/components/BeagleInput.spec.tsx
> +  expect(wrapper.props().value).not.toContain('Changed')
I changed to find the HTML element, then get the HTML input value.  

I changed the value I check on the component's renderization, to make sure the input value was empty before the value change.

2020-10-24 02:23 UTC, osmarpetry commented on packages/beagle-react/src/__tests__/components/BeagleInput.spec.tsx
> +  expect(wrapper.props().value).toContain('Changed')
For sure! I didn't think I was just testing the Component's props, instead of input's HTML value

2020-10-24 02:24 UTC, osmarpetry commented on packages/beagle-react/src/__tests__/components/BeagleInput.spec.tsx
> +  expect(wrapper.props().value).not.toContain('Changed')
I changed to check the HTML value

2020-10-24 02:24 UTC, osmarpetry commented on packages/beagle-react/src/__tests__/components/BeagleInput.spec.tsx
> +  wrapper.simulate('change', { target: { value: 'Changed' } })
Thanks!

2020-10-24 02:29 UTC, osmarpetry commented on packages/beagle-react/src/__tests__/components/BeagleInput.spec.tsx
> +  expect(wrapper.props().value).not.toContain('Changed')
For sure! It's an alternative to this test, because I'm already testing what onChange does on the previous test, so I just need to check if it isn't called anymore

2020-10-24 02:30 UTC, osmarpetry commented on packages/beagle-react/src/__tests__/components/BeagleInput.spec.tsx
> +  var inputStateValue = ''
Done like the previous

2020-10-24 02:37 UTC, osmarpetry commented on packages/beagle-react/src/__tests__/components/BeagleTabBar.spec.tsx
> +  let wrapper = mount(
It's done!

2020-10-24 03:18 UTC, osmarpetry commented on packages/beagle-react/src/components/BeagleInput/index.tsx
> +    if (!disabled && !readOnly) {
I agree with you, but the disabled and read-only just works as expected if I put the behavior in the JS code.

If this JS alteration is okay, I can keep the tests like they are. If not, will be removing the disabled and readonly tests. If yes, I will work on onFocus and onBlur too.

2020-10-24 03:20 UTC, osmarpetry commented on packages/beagle-react/src/components/TextArea/index.tsx
> +    if (!disabled) {
I answered the comment on input's comment too.

2020-10-24 03:28 UTC, osmarpetry commented on packages/beagle-react/src/components/BeagleTabBar/index.tsx
> +            aria-label={item.title}
![https://media3.giphy.com/media/LXr2Uxk2xUO2I/giphy.gif](https://media3.giphy.com/media/LXr2Uxk2xUO2I/giphy.gif)

2020-10-24 04:37 UTC, osmarpetry commented on packages/beagle-react/src/__tests__/components/Modal.spec.tsx
> +  let closed = false
I don't know what could be the alternative to modal tests. Because I should check if the HTML is rendered, and if I can toggle the modal because you can create a modal that just close or just open one time

2020-10-24 04:38 UTC, osmarpetry commented on packages/beagle-react/src/__tests__/components/Modal.spec.tsx
> +  const onClickClosedMock = () => (closed = !closed)
The intentation is the make the toggle of the modal, I told in the previous comment

2020-10-24 04:38 UTC, osmarpetry commented on packages/beagle-react/src/__tests__/components/Modal.spec.tsx
> +  const onClickOpenedMock = () => (opened = !opened)
The intention is the make the toggle of the modal, I told in the next comment

2020-10-24 04:39 UTC, osmarpetry commented on packages/beagle-react/src/components/TextArea/index.tsx
> +    if (!disabled) {
I will repeat the input tests and JS implementation in the textarea too

2020-10-28 17:18 UTC, Tiagoperes commented
Osmar, the PR validation has been corrected here in Beagle-React. Now it should fail only if there really is a problem with the code. The linter is accusing an error, please run `yarn lint` and fix it.

2020-10-29 20:52 UTC, Tiagoperes requested changes

2020-10-29 20:52 UTC, Tiagoperes commented on packages/beagle-react/src/__tests__/components/Modal.spec.tsx
> +  const onClickOpenedMock = () => (opened = !opened)
what I meant is: what the function does is making no difference, since you never click the button to close the modal.

If instead of `const onClickOpenedMock = () => (opened = !opened)` you wrote `const onClickOpenedMock = () => console.log('blah')`, the test would still pass.

If you want to create a function just for the sake of passing it as a parameter, to make it clear that what the function does doesn't matter, you should use `jest.fn()`.

Instead, I would just remove this line and, when mounting the component, use `jest.fn()`:

```typescript
<Modal onClose={jest.fn()} isOpen={opened}>
    Opened modal
</Modal>
```

2020-10-29 20:52 UTC, Tiagoperes commented on packages/beagle-react/src/__tests__/components/Modal.spec.tsx
> +  let closed = false
The ideal test suit would be:

1. Should render (snapshot)
2. Should start opened
3. Should start closed
4. Should toggle modal visibility (open => closed => open)
5. Should handle onClose event

Anyway, this would be the ideal, but you don't need to do it. I will still accept this PR once the other issues are corrected.

2020-10-29 20:52 UTC, Tiagoperes commented on packages/beagle-react/src/__tests__/components/Modal.spec.tsx
> +  const onClickClosedMock = () => (closed = !closed)
Same as before, use `jest.fn()` when it doesn't what the function does

2020-10-29 20:52 UTC, Tiagoperes commented on packages/beagle-react/src/components/BeagleInput/index.tsx
> +    if (!disabled && !readOnly) {
It is not ok. The behavior without this change works 100% in the browser. With this change, the behavior is broken because it makes inputs with readonly never execute the events "blur"  and "focus", which they should.

Even if the behavior was kept the same, it is not ok to add additional logic to the code only because of a test.

We know a disabled input will never fire the events "change", "focus" or "blur". This is part of the HTML specification. The job to test if a disabled input will or will not fire these events is of Chrome, Opera, Firefox, etc, not ours. Our job is to check if the input correctly received the attribute "disabled", if it has, then it's fine, the browser is guaranteed to work.

The same is valid for readonly. We know a readonly input will never fire a "change" event, we don't need to test this. The only thing we need to test is: when we pass `readonly = true` is the input html element rendered with the attribute "readonly"?

2020-11-02 19:57 UTC, osmarpetry commented
I did the asked alterations, If I did forget something, tell me

2020-11-09 13:57 UTC, Tiagoperes commented
Osmar, although your PR is fine, the tests are failing when trying to merge this branch with our master. I'll change the target branch of this PR to a new branch, accept it, and check what's  goin on.

2020-11-09 13:59 UTC, Tiagoperes approved these changes

2020-11-09 13:59 UTC, merged