Splits screen component from container component
ZupIT/beagle-web-react pull request #163
Opened 2020-10-26 12:58 UTC by hectorcustodiozup

**- What I did**
Separated the screen component from the container component
**- How I did it**
Created new interface and components
**- How to verify it**

**- Description for the changelog**

2020-10-27 14:20 UTC, Tiagoperes requested changes

2020-10-27 14:20 UTC, Tiagoperes commented on packages/beagle-react/src/components/BeagleScreen/index.tsx
> +    if (onInit) onInit()
remover

2020-10-27 14:20 UTC, Tiagoperes commented on packages/beagle-react/src/components/BeagleScreen/styled.ts
> +	display: flex;
substituir tab por espaços

2020-10-27 14:20 UTC, Tiagoperes commented on packages/common/models/beagle-screen.model.ts
> +  onInit?: () => void,
Screen não tem `onInit`

2020-10-27 14:45 UTC, hectorcustodiozup commented on packages/beagle-react/src/components/BeagleScreen/styled.ts
> +	display: flex;
Se for indentação, está correto no código, acho que o git que alterou

2020-10-27 14:57 UTC, Tiagoperes submitted a review, later dismissed

2020-10-27 15:03 UTC, carolinegoncalveszup commented on packages/common/models/beagle-screen.model.ts
> +export interface BeagleScreenInterface extends BeagleDefaultComponent {
Eu acho que não precisamos que o screen extenda do BeagleDefaultComponent já que o screen não recebe nem style nem classe

2020-10-27 15:08 UTC, carolinegoncalveszup commented on packages/beagle-react/src/components/index.ts
> +  'beagle:screen': BeagleScreen,
Nesse objeto tem uma entrada `'beagle:screencomponent': BeagleContainer,` acho que ela deveria ser alterada ao invés de criar uma nova não?

2020-10-27 15:14 UTC, carolinegoncalveszup commented on packages/beagle-react/src/components/BeagleScreen/index.tsx
> +export default withTheme(BeagleScreen)
Considerando que o screen não vai receber nem style nem classe, acho que não precisamos usar o withTheme

2020-10-28 17:15 UTC, Tiagoperes approved these changes

2020-10-28 17:43 UTC, carolinegoncalveszup approved these changes

2020-10-28 17:49 UTC, merged