Feature/script init
ZupIT/beagle-web-react pull request #175
Opened 2021-01-15 19:06 UTC by jamessonpenhazup

**- What I did**
I developed an init script, this script creates the initial settings for using Beagle
**- How I did it**
Using the Node File System
**- How to verify it**
Create a new project and run 'beagle' command  in the terminal
**- Description for the changelog**

2021-01-18 12:33 UTC, hectorcustodiozup commented on packages/beagle-react/cli/init/index.js
> +  rl.question('Want to replace app.tsx with the Beagle configuration (y or n) ?', (answer) => {
Usar aqui o formato de pergunta no presente simples
e.g: Do you want to replace 'app.tsx' content with the Beagle configuration (y or n)?

2021-01-18 12:34 UTC, hectorcustodiozup requested changes
Apenas um erro de gramática na pergunta de alteração dos arquivos. 

E um ponto que não sei se é da minha configuração local, mas não consegui rodar o comando apenas com beagle (Como descrito na PR) precisei colocar o yarn: yarn beagle

2021-01-19 17:24 UTC, Tiagoperes requested changes

2021-01-19 17:24 UTC, Tiagoperes commented on packages/beagle-react/cli/init/index.js
> +      data = await fsPromises.readFile(path, (err, data) => {
Ao usar o fs.promises, utilize a sintaxe async/await e não callbacks. Isso simplifica bastante seu código e elimina a necessidade de função `readFileContent`.

```typescript
const fileOptions = { encoding: 'utf8' }

(async () => {
  const beagleContent = await fsPromises.readFile(__dirname + '/boilerplate/beagle-service.ts', fileOptions)
  const appContent = await fsPromises.readFile(__dirname + '/boilerplate/app.tsx', fileOptions)
  // ...
})()

2021-01-19 17:24 UTC, Tiagoperes commented on packages/beagle-react/cli/init/index.js
> +  fs.writeFile('src/beagle/beagle-service.ts', beagleContent, function (err) {
utilize `fs.promises`, espere a escrita terminar para continuar e especifique a codificação do texto ao escrever o arquivo.

```typescript
await fsPromises.writeFile('src/beagle/beagle-service.ts', beagleContent, fileOptions)
```

2021-01-19 17:24 UTC, Tiagoperes commented on packages/beagle-react/cli/init/index.js
> +      fs.writeFile('src/app.tsx', appContent, function (err) {
Utilize fsPromises

2021-02-08 21:21 UTC, arthurbleilzup approved these changes

2021-02-11 12:23 UTC, hectorcustodiozup commented
I tested it locally and the only thing I noticed is that if I change anything in the beagle service file and then run the script again all my modifications are replaced. I do not know if it is possible but maybe later we could add a verification and alert the user like so:
You already have a beagle configuration, are you sure you want to replace it?

2021-02-11 12:26 UTC, hectorcustodiozup approved these changes

2021-02-11 17:49 UTC, Tiagoperes approved these changes

2021-02-12 18:42 UTC, merged