Fix/retry beagle error
ZupIT/beagle-web-react pull request #176
Opened 2021-01-26 13:51 UTC by Bleil

**- What I did**
Following the pattern of the component on the Android environment, I created the same behavior on the component, allowing the user to retry the action that he was trying to do. Also, I added the errors list, that is provided by the core, showing to the user what could happened.

P.S.: The detailed messages are hidden and only will be displayed if the user clicks on "Show details".

**- How I did it**
Followed the pattern of components already developed on the project, keeping the behavior of Android environment and added useful information about what happened, giving details about the errors.

**- How to verify it**

1. After building the project, link it using yarn and create a new React project installing beagle. 
2. Then link your built project
3. On your test React project, create a JSON with this content:
`{
            "_beagleComponent_": "beagle:lazycomponent",
            "path": "/listview.json",
            "initialState": {
                "_beagleComponent_": "beagle:text",
                "text": "Loading the screen, please wait",
                "textColor": "grey",
                "alignment": "CENTER"
            }
        }`
4.  Then start your application, it should display the error message, because we do not have created the "listview.json" that _beagle:lazycomponent_ requires, showing you the error component.

**- Description for the changelog**

2021-02-05 17:38 UTC, Tiagoperes requested changes

2021-02-05 17:38 UTC, Tiagoperes commented on packages/beagle-react/package.json
> +    "@types/react-native": "^0.63.46",
pq essas dependências do RN?

2021-02-05 17:38 UTC, Tiagoperes commented on packages/beagle-react/src/components/BeagleError/index.tsx
> +        onClick={() => retry()}
pode passar só `retry` aqui `onClick={retry}`

2021-02-05 17:38 UTC, Tiagoperes commented on packages/beagle-react/src/components/BeagleError/index.tsx
> +            onClick={() => handleShowMore()}
`onClick={handleShowMore}`

2021-02-05 17:38 UTC, Tiagoperes commented on packages/beagle-react/src/components/commons.styled.ts
> +export const StyledButton = styled.button`
Ao invés de transferir esses estilos de lugar, não seria melhor vc ter usado o componente `<BeagleButton>`?

2021-02-06 19:19 UTC, arthurbleilzup commented on packages/beagle-react/package.json
> +    "@types/react-native": "^0.63.46",
estava indo testar o RN, mas estava na pasta errada, esqueci de remover a dep errada

2021-02-06 19:19 UTC, arthurbleilzup commented on packages/beagle-react/src/components/BeagleError/index.tsx
> +        onClick={() => retry()}
resolvido

2021-02-06 19:19 UTC, arthurbleilzup commented on packages/beagle-react/src/components/commons.styled.ts
> +export const StyledButton = styled.button`
resolvido

2021-02-08 18:16 UTC, hectorcustodiozup submitted a review, later dismissed

2021-02-11 17:47 UTC, Tiagoperes submitted a review, later dismissed

2021-02-11 18:52 UTC, hectorcustodiozup approved these changes

2021-02-11 19:07 UTC, Tiagoperes approved these changes

2021-02-11 19:07 UTC, merged