Feature/form validation
ZupIT/beagle-web-react pull request #177
Opened 2021-01-28 12:40 UTC by hectorcustodiozup

**- What I did**
Following the EPIC (https://github.com/ZupIT/beagle/issues/883) added form error validation

**- How I did it**
Altered the components Input and SimpleForm to accept two new properties 'error' and showError'

**- How to verify it**
Run this branch and pass the two new properties to the component

**- Description for the changelog**
Adds form validation

2021-02-05 20:15 UTC, Tiagoperes requested changes

2021-02-05 20:15 UTC, Tiagoperes commented on packages/beagle-react/src/components/BeagleInput/index.tsx
> +  const errorColor = '#FF0000'
Try no to add styles outside the styled.ts file

2021-02-05 20:15 UTC, Tiagoperes commented on packages/beagle-react/src/components/BeagleInput/index.tsx
> +  const borderWithError: React.CSSProperties = {
same

2021-02-05 20:15 UTC, Tiagoperes commented on packages/beagle-react/src/components/BeagleInput/index.tsx
> +      showError = true
You should let beagle control this, it's not our place to control the error

2021-02-06 23:04 UTC, hectorcustodiozup commented on packages/beagle-react/src/components/BeagleInput/index.tsx
> +  const errorColor = '#FF0000'
I was using this variable to pass the red color to the BeagleText component. I removed the variable and passed it directly instead.

2021-02-06 23:08 UTC, hectorcustodiozup commented on packages/beagle-react/src/components/BeagleInput/index.tsx
> +  const borderWithError: React.CSSProperties = {
If I am not mistaken we have an opened issue to remove the styled dependency, thinking of that I decided not to use it. Nevertheless I created the styled file for the input component

2021-02-08 21:19 UTC, arthurbleilzup requested changes

2021-02-08 21:19 UTC, arthurbleilzup commented on packages/beagle-react/src/components/BeagleInput/index.tsx
> +        textColor={'#FF0000'}
Because the color is required as a validation test, I suggest to use a variable on the commons.styled.ts or even inside component's style

2021-02-08 21:19 UTC, arthurbleilzup commented on packages/beagle-react/src/components/BeagleInput/styled.ts
> +`
same color variable as above

2021-02-08 21:37 UTC, arthurbleilzup submitted a review, later dismissed

2021-02-08 21:38 UTC, hectorcustodiozup commented on packages/beagle-react/src/components/BeagleInput/index.tsx
> +        textColor={'#FF0000'}
FIxed

2021-02-11 17:35 UTC, Tiagoperes commented on packages/beagle-react/src/components/BeagleInput/index.tsx
> +  const borderWithError: React.CSSProperties = {
When we remove it, we'll replace it with plain css. It is pretty straight forward to convert styled.ts files into css. It is much harder if we have to read every file identifying styles that have been declared directly into the code.

2021-02-11 17:43 UTC, Tiagoperes submitted a review, later dismissed

2021-02-11 17:45 UTC, Tiagoperes approved these changes

2021-02-11 17:53 UTC, arthurbleilzup approved these changes

2021-02-12 18:39 UTC, merged