Feature/accessibility
ZupIT/beagle-web-react pull request #181
Opened 2021-02-11 14:58 UTC by arthurbleilzup

**- What we did** (@jamessonpenhazup and I)
Added support to the Accessibility object that comes from BFF and also implemented accessibility attributes on beagle components (may help some disabled people)

**- How we did it** (@jamessonpenhazup and I)
Created a function that builds the new accessibility attributes for components and created a map to make easier the insertion of new attributes

**- How to verify it** (@jamessonpenhazup and I)
When you create an Accessibility object on BFF, should be `accessible: true`, provide `accessibilityLabel` with some text, and the element that you expect should come with `aria-label="your text"`. If you also provide the `isHeader: true` attribute, you should see that your element will come with the attribute defined as `role="heading"`

2021-02-11 14:59 UTC, jamessonpenhazup submitted a review, later dismissed

2021-02-12 18:29 UTC, Tiagoperes requested changes
As discussed via ms teams, some `aria-*` properties that have been added are redundant. Although removing them is not necessary for the approval of this PR, it would be nice to have them removed.

The only commentary in the code is a set of observations and tips. Also not required for approval.

Unfortunately, I did find some problems and I don't think they should make into master. They are:

- The type `Accessibility` should represent better the backend structure, i.e. there should not be `[key: string]: unknown`
- When converting `Accessibility` to a map of accessibility properties (`Record<string, string>`), the real values of the parameter `a11y: Accessibility` are not fully considered.
    - if a11y.accessible is false, the accessibility properties are generated anyway. I expected them to be an empty object (`{}`) in this case.
    - if a11y.isHeader is false, the attribute `role: 'heading'` is generated anyway. I expected this attribute not to be generated in this case.
- There should unit tests that test this function directly, without mounting any component.

I don't think you should try to make it generic supposing it will one day be altered by the backend. If it does get altered, the truth is that we can't possibly know what the changes are gonna be and chances are we'll have to update the front-end anyway.

Here's a suggestion based on the code I previously suggested for `buildAccessibility`:

```typescript
const handlers: Record<keyof Accessibility, (a11y: Accessibility) => A11YAttr | null> = {
  accessibilityLabel: ({ accessibilityLabel }) => accessibilityLabel ? 
    { value: accessibilityLabel || '', qualifiedName: 'aria-label' }
    : null,
  accessible: () => null,
  isHeader: ({ isHeader }) => isHeader ? { qualifiedName: 'role', value: 'heading' } : null,
}

const notAccessible: Accessibility = { accessible: false }

export const buildAccessibility = (a11y = notAccessible): Record<string, string> => {
  if (!a11y.accessible) return {}
  const keys = Object.keys(a11y) as (keyof Accessibility)[]
  return keys.reduce((result, key) => {
    const attr = handlers[key](a11y)
    return attr ? { ...result, [attr.qualifiedName]: attr.value } : result
  }, {})
}
```

Above, the use of `as` is ok, because we are 100% sure the cast is correct.

2021-02-12 20:29 UTC, Tiagoperes approved these changes

2021-02-18 12:26 UTC, hectorcustodiozup approved these changes

2021-02-19 18:53 UTC, merged