Deprecated field disabled
ZupIT/beagle-web-react pull request #189
Opened 2021-03-24 18:15 UTC by tayronemachadozup

Issue https://github.com/ZupIT/beagle/issues/1401

**- What I did**
Create field enabled in text input and deprecated field disabled

**- How to verify it**
Was tested through a react poc

2021-03-24 18:24 UTC, arthurbleilzup approved these changes

2021-03-24 18:26 UTC, arthurbleilzup requested changes

2021-03-24 18:26 UTC, arthurbleilzup commented on packages/beagle-react/src/__tests__/components/BeagleInput.spec.tsx
> -  enabled: false,
why remove enabled if we are deprecating disable?

2021-03-24 19:33 UTC, tayronemachadozup commented on packages/beagle-react/src/__tests__/components/BeagleInput.spec.tsx
> -  enabled: false,
Because the tests were breaking. The problem was resolved by updating the snapshot

2021-03-24 19:34 UTC, arthurbleilzup submitted a review, later dismissed

2021-04-06 20:16 UTC, Tiagoperes requested changes

2021-04-06 20:16 UTC, Tiagoperes commented on packages/beagle-react/src/components/BeagleInput/index.tsx
> +  const [isEnabled, setIsEnabled] = useState<boolean>(true)
You don't need a state for this. Just use the value directly in the button component. See the next commentary.

2021-04-06 20:16 UTC, Tiagoperes commented on packages/beagle-react/src/components/BeagleInput/index.tsx
> +        disabled={!isEnabled}
`disabled={enabled === false || disabled === true}`

no state needed

2021-04-06 20:16 UTC, Tiagoperes commented on packages/beagle-react/src/components/BeagleInput/index.tsx
> +        aria-disabled={!isEnabled}
same.

If you don't want to repeat the condition, you can declare this in a variable before returning this JSX.

2021-04-06 20:16 UTC, Tiagoperes commented on packages/common/models/beagle-input.model.ts
> +  *  Use field enabled to control is enabled or not in this layout.
Please, correct this text according to what has been discussed in the equivalent PR for Angular.

2021-04-12 14:08 UTC, arthurbleilzup approved these changes

2021-04-12 14:11 UTC, arthurbleilzup requested changes
Before commit everything, run on your machine `yarn test -u` to update your snapshots, no needing to remove things manually

2021-04-12 19:11 UTC, Tiagoperes approved these changes

2021-04-12 19:11 UTC, arthurbleilzup approved these changes

2021-04-12 19:11 UTC, merged