fix script init
ZupIT/beagle-web-react pull request #192
Opened 2021-04-15 20:49 UTC by jamessonpenhazup

**- What I did**
I made the necessary corrections for the script to work on all projects, even on a totally default project with no folder created. I also changed the name of the App.tsx file to app.tsx. Closes #191
**- How I did it**
If there is no folder, the script generates the src and the beagle
**- How to verify it**
1. start a project from scratch by creating a new directory named project
2. cd project
3. yarn init: use all default options (enter)
4. yarn add react
5. yarn add @zup-it/beagle-react
6. yarn beagle init
**- Description for the changelog**

2021-04-16 12:21 UTC, Tiagoperes requested changes
An observation: **no need to change anything**, it's just a tip for the next time: callbacks are ugly, instead of using the module `fs`, you could use `fs/promises` and write your code with async/await.

2021-04-16 12:21 UTC, Tiagoperes commented on packages/beagle-react/cli/init/index.js
> +}
You don't need to create multiple ifs here, you only need the following line of code:

```typescript
fs.mkdirSync(dir, { recursive: true })
```

The line above does all of the following:
- it checks if the directory already exists and does nothing in case it exists
- creates any directory in the path, recursively. So, if `/src` doesn't exist, it will create it.

2021-04-16 13:47 UTC, arthurbleilzup requested changes

2021-04-16 13:47 UTC, arthurbleilzup commented on packages/beagle-react/cli/init/index.js
> +      }
Using the tips that @Tiagoperes gave to you, about `fs/promises`, you can also abstract those `fs.writeFile` into a method that returns a `Promise` and handle those `throw`, because they are currently uncaught.

```suggestion
async function createAppTsx(path: string, content: string): Promise<void> {
  try {
    await writeFile(`${path}/app.tsx`, content)
  } catch (error) {
    console.error(error)
    process.exit()
  }
}

// using it
// { ... }
if (`${answer}` === 'y') {
    await createAppTsx('src', appContent)        
}
process.exit()
```

2021-04-16 13:47 UTC, arthurbleilzup commented on packages/beagle-react/cli/init/index.js
> +      }
PS: do not commit this suggestion... made it a suggestion to be more easy to visualize

2021-04-20 15:10 UTC, Tiagoperes requested changes
I just noticed you do import `fsPromises`. You're using both promises and callbacks to do the same thing. This is very confusing. Please update your code to use only fsPromises.

Since you're at it, replace `mkdirSync` with mkdir from `fs/promises`, it is always better to treat async operation as async processes.

2021-04-20 15:10 UTC, Tiagoperes commented on packages/beagle-react/cli/init/index.js
> +fs.mkdirSync(dir, { recursive: true })
I don't think you understood it correctly.

Please, call mkdirSync only once!

```typescript
fs.mkdirSync(`${dir}/beagle`, { recursive: true })
```

after doing this, you can be sure `src/beagle` exists, no matter if `/src` exists or not (the directory has been created recursively).

The lines 9 to 11 don't need to exist.

2021-04-22 14:18 UTC, arthurbleilzup requested changes

2021-04-22 14:18 UTC, arthurbleilzup commented on packages/beagle-react/cli/init/index.js
> +  }
So, in this peace of code, I see that you are using `fs.existsSync`, but this method is deprecated, see here: [fs.exists is deprecated](https://github.com/verdaccio/monorepo/issues/60). 

So the new method that I suggest to use is `access`, which exists inside `fs/promises`. The implementation of `access`, does not return a `boolean`, if the path or the file does not exists, it rejects the `Promise`, as we are using `async/await`, this method should be inside a `try/catch` block, because when the `Promise.reject()` is called, it will be catched by the `catch` statement, if it exists, the rest of the code inside the `try` statement will be executed normally, so that's why we `return true || return false` that is the same as `Promise.resolve(true) || Promise.resolve(false)`. If you want to reject the promise, you can simply `throw new Error('My error message')`, that is the same as `Promise.reject(new Error('My error message'))`.

Now, considering that you used the destructuring above, here is my suggestion how it would be nice to be implemented:

```suggestion
  const appTsxExists = async (path) => {
     try {
       await access(`${path}/app.tsx`, constants.F_OK)
       return true
     } catch (error) {
       logger.error(error)
       return false
     }
  }

  const appFileExists = await appTsxExists(dir)
  if (!appFileExists) {
    createAppTsx(dir, appContent)
  }
```

2021-04-22 18:09 UTC, Tiagoperes submitted a review, later dismissed
Just check Arthur's comments pls

2021-04-22 18:15 UTC, Tiagoperes approved these changes

2021-04-22 18:55 UTC, arthurbleilzup approved these changes

2021-04-22 18:57 UTC, merged