With this change nothing will overlap the modal
ZupIT/beagle-web-react pull request #193
Opened 2021-04-19 12:30 UTC by gabrielpenhazup

- What did I do
I made the necessary corrections so that no component overlaps the modal. Closes #190

2021-04-19 14:32 UTC, tayronemachadozup commented
Gabriel run `yarn test -u` command to correct the failing snapshot test and follows the description patterns of a pr.

2021-04-19 15:12 UTC, arthurbleilzup requested changes
Please run the command that @tayronearaujo mentioned on your machine, to update your tests snapshots and then commit it again to have this PR approved

2021-04-19 15:12 UTC, arthurbleilzup commented on packages/beagle-react/src/components/Modal/styled.ts
> +  z-index: 1;
I was wondering about this change and trying to think if there was a scenario where `z-index: 1` wouldn't be effective... well, beyond the Beagle elements it will not impact, only `BeagleModal` uses that behavior. 

On other hand, the developers that use Beagle can develop components that overlap this change, but there are more than one solution for that, that are the users implementing their features differently or overriding the style of `BeagleModal`, so I believe this is a good solution.

Ps. Sorry for the long text, just leaving my thoughts here, as reflection for next features...

2021-04-19 18:33 UTC, arthurbleilzup approved these changes

2021-04-20 14:59 UTC, Tiagoperes approved these changes

2021-04-20 14:59 UTC, merged