Feature/gridview
ZupIT/beagle-web-react pull request #195
Opened 2021-04-27 12:52 UTC by hectorcustodiozup

**- What I did**
Added new component beagle:gridview

**- How I did it**
Separated the listview logic and common interface in a new core component that is shared between the Listview and the new Gridview.

The Listview and GridView components now have their own interfaces with whichever properties they need.

**- How to verify it**
Use the new component beagle:gridview and pass its new property numColumns

Result:
![image](https://user-images.githubusercontent.com/50678762/116243669-8d46c080-a73d-11eb-9d1a-44a5380b4dc4.png)

**- Description for the changelog**

2021-05-05 15:26 UTC, arthurbleilzup requested changes

2021-05-05 15:26 UTC, arthurbleilzup commented on packages/common/models/dynamicLists-core.model.ts
> +export type ListType = 'GRID' | 'LIST'
On TypeScript, we are able to create [String Enums](https://www.typescriptlang.org/docs/handbook/enums.html#string-enums), so would be a cleaner approach to use on the application, avoiding some casts using `as` and is easier to do maintenance and for new types of dynamic list. Other benefits are the ability to quickly find all references to the list type on the whole project structure and it is also really quicker to write, because using the auto-complete of your editor you do not have to worry about misspelling the string or validating it.

I suggest implement this (also valid for Direction) like this:

```suggestion
export enum ListType {
  Grid='GRID',
  List='LIST'
}

export enum ListDirection {
  Horizontal='HORIZONTAL',
  Vertical='VERTICAL'
}
```

Then, when you would use this enum, you simply use like this:
```javascript
listType: ListType.Grid
// OR
listType: ListType.List
```

2021-05-05 15:26 UTC, arthurbleilzup commented on packages/beagle-react/src/components/BeagleDynamicLists/DynamicListCore/styled.ts
>    height: ${({ direction }) => direction === 'VERTICAL' ? '100%' : 'auto'};
Based on the suggestion of using a String Enum, instead of two strings as type, I suggest changing here to this approach (also using this opportunity to do the same change on direction):

```suggestion
export const StyledDynamicViewsInterface = styled.div<StyledDynamicViewsInterface>`
  display: ${({ listType }) => listType === ListType.Grid ? 'grid' : 'flex'};
  grid-template-columns: ${({ listType, numColumns }) => 
    (listType === ListType.Grid && numColumns) && `repeat(${numColumns}, auto)`};
  justify-content: ${({ listType })=> listType === ListType.Grid && 'space-evenly'};
  flex-direction: ${({ direction }) => direction === ListDirection.Vertical ? 'column' : 'row'};
  overflow: ${({ useParentScroll }) => useParentScroll ? 'inherit' : 'auto'};
  width: ${({ direction }) => direction === ListDirection.Horizontal ? '100%' : 'auto'};
  height: ${({ direction }) => direction === ListDirection.Vertical ? '100%' : 'auto'};
```

2021-05-05 15:26 UTC, arthurbleilzup commented on packages/beagle-react/src/components/BeagleDynamicLists/DynamicListCore/index.tsx
> +        })
Based on the suggestion of using String Enums (down on this PR), I suggest:

```suggestion
          [direction === ListDirection.Vertical ?
            'aria-rowcount' : 'aria-colcount']: Children.count(children) || 0,
        })
```

2021-05-05 15:26 UTC, arthurbleilzup commented on packages/beagle-react/src/components/BeagleDynamicLists/DynamicListCore/index.tsx
>    direction = 'VERTICAL',
Based on the suggestion of using String Enums (down on this PR), I suggest:

```suggestion
  direction = ListDirection.Vertical,
```

2021-05-05 15:26 UTC, arthurbleilzup commented on packages/beagle-react/src/components/BeagleDynamicLists/BeagleListView/index.tsx
> +    listType: 'LIST' as ListType,
Based on the suggestion of using String Enums (down on this PR), wouldn't be necessary a cast, I suggest:

```suggestion
    listType: ListType.List,
```

2021-05-05 15:26 UTC, arthurbleilzup commented on packages/beagle-react/src/components/BeagleDynamicLists/BeagleGridView/index.tsx
> +    listType: 'GRID' as ListType,
Based on the suggestion of using String Enums (down on this PR), wouldn't be necessary a cast, I suggest:

```suggestion
    listType: ListType.Grid,
```

2021-05-06 13:56 UTC, hectorcustodiozup commented on packages/common/models/dynamicLists-core.model.ts
> +export type ListType = 'GRID' | 'LIST'
As Tiago pointed out on this PR https://github.com/ZupIT/beagle-web-angular/pull/245. We avoid using enums on the projects so I am resolving the related requests

2021-05-14 20:37 UTC, Tiagoperes requested changes
Overall commentaries:

As of now both the ListView and the GridView accept `listType` as parameter. This should not be the case, since only the parent component accepts this attribute.

If your types are all correct you should not need the casts you made for the ListType, please, check them, the casting should not be necessary.

2021-05-14 20:37 UTC, Tiagoperes commented on packages/beagle-react/src/components/BeagleDynamicLists/DynamicListCore/styled.ts
> +const screenSize = document.body.clientWidth
This is not gonna work if the screen gets resized. Have you tried used `1fr` as the column width instead?

2021-05-14 20:37 UTC, Tiagoperes commented on packages/beagle-react/src/components/BeagleDynamicLists/DynamicListCore/index.tsx
> +interface DynamicViewInterface extends BeagleListViewInterface, BeagleGridViewInterface { }
some linters prohibits empty interfaces. This is not our case, you can leave the code like this, it's not a problem. But another way to say the same thing without creating an empty interface would be `type DynamicViewInterface = BeagleListViewInterface & BeagleGridViewInterface`

2021-06-08 14:44 UTC, Tiagoperes submitted a review, later dismissed

2021-06-08 14:46 UTC, tayronemachadozup submitted a review, later dismissed

2021-06-08 14:58 UTC, Tiagoperes approved these changes

2021-06-08 15:01 UTC, tayronemachadozup approved these changes

2021-06-08 15:02 UTC, merged