Fix/beagle init
ZupIT/beagle-web-react pull request #204
Opened 2021-06-09 19:52 UTC by jamessonpenhazup

**- What I did**
Fixed the beagle init script that replaces beagle-service.ts without asking.
**- How I did it**
Added ask to replaces beagle-service.ts.
**- How to verify it**
Run yarn beagle
Run yarn beagle again
The program will ask if we really want to replace "app.tsx"
The program will ask if we really want to replace "beagle-service.ts"
**- Description for the changelog**
Closes #202

2021-06-09 20:50 UTC, arthurbleilzup requested changes
I saw some room for improvements on your code, making it simpler and more cleaner, please be free to follow the suggestions and test them out!

2021-06-09 20:50 UTC, arthurbleilzup commented on cli/init/index.js
> +
```suggestion
const appTsx = 'app.tsx'
const beagleServicePath = 'beagle/beagle-service.ts'
```

2021-06-09 20:50 UTC, arthurbleilzup commented on cli/init/index.js
> +      await createFile(`${dir}/app.tsx`, appContent)
```suggestion
      await createFile(`${dir}/${appTsx}`, appContent)
```

2021-06-09 20:50 UTC, arthurbleilzup commented on cli/init/index.js
> +        await createFile(`${dir}/app.tsx`, appContent)
```suggestion
        await createFile(`${dir}/${appTsx}`, appContent)
```

2021-06-09 20:50 UTC, arthurbleilzup commented on cli/init/index.js
> +    await createFile(`${dir}/beagle/beagle-service.ts`, beagleContent)
```suggestion
    await createFile(`${dir}/${beagleServicePath}`, beagleContent)
```

2021-06-09 20:50 UTC, arthurbleilzup commented on cli/init/index.js
> +        await createFile(`${dir}/beagle/beagle-service.ts`, beagleContent)
```suggestion
        await createFile(`${dir}/${beagleServicePath}`, beagleContent)
```

2021-06-09 20:50 UTC, arthurbleilzup commented on cli/init/index.js
> +      await access(`${path}/beagle/beagle-service.ts`, constants.F_OK)
```suggestion
      await access(`${path}/${beagleServicePath}`, constants.F_OK)
```

2021-06-09 20:50 UTC, arthurbleilzup commented on cli/init/index.js
>        if (`${answer}` === 'y' || `${answer}` === 'Y') {
```suggestion
      if (new RegExp(`^${answer}$`, 'i').test('y')) {
```

2021-06-09 20:50 UTC, arthurbleilzup commented on cli/init/index.js
> +      if (`${answer}` === 'y' || `${answer}` === 'Y') {
```suggestion
      if (new RegExp(`^${answer}$`, 'i').test('y')) {
      if (`${answer}` === 'y' || `${answer}` === 'Y') {
```

2021-06-09 20:52 UTC, igorgiumellizup commented on cli/init/index.js
> +      console.error("beagle/beagle-service.ts did not exist, it was created with Beagle settings.")
```suggestion
      console.error("beagle/beagle-service.ts not found! Beagle settings used instead")
```

2021-06-09 20:52 UTC, igorgiumellizup reviewed
.

2021-06-10 12:05 UTC, Tiagoperes commented on cli/init/index.js
> +      console.error("beagle/beagle-service.ts did not exist, it was created with Beagle settings.")
Why is this an error log? Isn't expected that this file doesn't exist?

2021-06-14 13:25 UTC, arthurbleilzup requested changes
Just some final details and we are good to go

2021-06-14 13:25 UTC, arthurbleilzup commented on cli/init/index.js
> +      }
```suggestion
      if (new RegExp(`^${answer}$`, 'i').test('y')) {
         await createFile(`${dir}/app.tsx`, appContent)
         console.log("success! all configuration files were created correctly")
         process.exit()
      }
```
We have an unnecessary `if` here

2021-06-14 13:25 UTC, arthurbleilzup commented on cli/init/index.js
> +    return exists
```suggestion
    return await existsSync(`${path}/${beagleServicePath}`)
```
You can return the result directly without a variable

2021-06-15 19:45 UTC, arthurbleilzup approved these changes

2021-06-30 18:17 UTC, Tiagoperes requested changes

2021-07-02 14:41 UTC, Tiagoperes approved these changes

2021-07-02 14:41 UTC, merged