Feature/grid view direction
ZupIT/beagle-web-react pull request #205
Opened 2021-06-25 12:49 UTC by hectorcustodiozup

**- What I did**
Added support to grdView direction property, according to the following issue https://github.com/ZupIT/beagle/issues/1640
**- How I did it**
 - Deprecated the old property numColumns
 - Changed the direction property from listview interface to the shared interface
 - Added new property to the gridview interface
 - Added styling rules to use these new properties
 
**- How to verify it**
Create a gridview component and add the new keys to its body

**- Description for the changelog**

2021-06-30 15:07 UTC, Tiagoperes requested changes

2021-06-30 15:07 UTC, Tiagoperes commented on packages/common/models/beagle-gridview.model.ts
> +   * @deprecated Since version 1.8.2. Will be deleted in version 2.0.
```suggestion
   * @deprecated Since version 1.9.0. Will be deleted in version 2.0.
```

2021-06-30 17:46 UTC, arthurbleilzup approved these changes

2021-07-01 20:58 UTC, Tiagoperes approved these changes

2021-07-01 21:09 UTC, merged