Remove deprecated code
ZupIT/beagle-web-react pull request #219
Opened 2021-09-03 17:41 UTC by jamessonpenhazup

**- What I did**

Removed deprecated code of all beagle react.

**- How I did it**

Removed all @deprecated code and checking for possible impacts.

**- How to verify it**

Was verified through unit tests, pocs with react and angular and E2E test.

**- Description for the changelog**

2021-09-09 13:02 UTC, Tiagoperes commented on packages/beagle-react/src/components/BeagleDynamicLists/DynamicListCore/index.tsx
> +      'aria-rowcount': Math.ceil(Children.count(children)),
Be careful when altering calculations like this. You should always think "what was it doing before?", "Is it still doing the same thing?", "This calculus still makes sense"?

1. What was it doing before?
It used to tell how many rows and how many columns would be displayed by the grid.

2. Is it still doing the same thing?
No. You removed the number of columns (aria-colcount) and stopped calculating the number of rows by setting it to the number of children.

3. This calculus still makes sense?
It doesn't make any sense. How could the number of rows be the total number of items in the grid? This only happens if the grid has a single column, which won't normally happen.
`Children.count` will always return an integer, why would you apply a rounding function? It also makes no sense.

You must still tell `aria-rowcount` and `aria-colcount` the amount of rows and columns of the grid. Please, fix this.

2021-09-09 20:38 UTC, arthurbleilzup requested changes

2021-09-09 20:38 UTC, arthurbleilzup commented on packages/beagle-react/src/components/BeagleButton/index.tsx
> +  const beagleAnalytics = beagleService
You can remove this constant and use `beagleService` directly on the code.

2021-09-09 20:38 UTC, arthurbleilzup commented on packages/beagle-react/src/components/BeagleDynamicLists/DynamicListCore/index.tsx
>      ] as TemplateManagerItem[]
You can improve this approach by using like this:
```typescript
const templateItems = (templatesRaw || []) as TemplateManagerItem[]
```

2021-09-09 20:58 UTC, arthurbleilzup approved these changes

2021-09-10 11:47 UTC, Tiagoperes approved these changes

2021-09-10 11:57 UTC, merged